version: "3"
x-depends_on: &depends_on
  - "redis"
  - "db"
services:
  vote:
    build: ./vote
    command: 
    - python 
    - app.py
    ports:
      - "5000:80"
    depends_on: *depends_on

  result:
    build: ./result
    command: 
    - nodemon 
    - server.js
    ports:
      - "5001:80"
    depends_on: *depends_on

  worker:
    build:
      context: ./worker
    depends_on: *depends_on

  redis:
    image: redis:alpine

  db:
    image: postgres:9.4
